server:
  domain: asus
  address: :8443 # Use a non-privileged port for development
  # Use defaults for cert paths
database:
  dsn: ./lingomarker_dev.db
session:
  secret_key: "a-better-secret-key-for-development-but-still-not-prod" # Change this!

# web: # Use defaults
# gemini: # Use defaults
